import type { ClassDashboard } from '@/features/dashboard/data/dashboard-fixture';

interface AiInsightsCardProps {
  dashboard: ClassDashboard;
}

/**
 * Presentational-only summary card. There is no AI/model behind this text —
 * it is a static, human-written observation derived from the same fixture
 * numbers shown elsewhere on the page, not a computed insight. Do not wire
 * this to a real inference call without a confirmed backend contract.
 */
export function AiInsightsCard({ dashboard }: AiInsightsCardProps) {
  const strongest = dashboard.performance.reduce((best, segment) =>
    segment.percentage > best.percentage ? segment : best,
  );

  return (
    <section
      aria-labelledby="ai-insights-heading"
      className="rounded-koyi-lg border-koyi-accent bg-koyi-accent/10 border-2 p-5"
    >
      <div className="flex items-center gap-2">
        <span
          aria-hidden="true"
          className="bg-koyi-accent flex size-7 items-center justify-center rounded-full text-xs font-semibold text-white"
        >
          AI
        </span>
        <h2 id="ai-insights-heading" className="text-koyi-text text-lg font-semibold">
          AI Insights
        </h2>
      </div>

      <p className="text-koyi-text mt-3 text-sm">
        Most of {dashboard.className} is performing at a {strongest.label.toLowerCase()} level, with{' '}
        {dashboard.attentionCount} students flagged for extra support this term.
      </p>

      <p className="text-koyi-muted mt-4 text-xs">
        Illustrative summary only — not generated by a live model.
      </p>
    </section>
  );
}
